export const gameData=[
    {
    "id": 1,
    "Sport_Name": "Hockey",
    "History": [
      "History:-",
      "The roots of hockey are buried deep in antiquity. Historical records show that a crude form of the game was played in Egypt 4,000 years ago and in Ethiopia around 1,000BC, whilst an ancient form of the game was also played in Iran inaround 2,000BC.Various museums offer evidence that a form of the game was played by the Romans and Greeks as well as by the Aztecs several centuries before Columbus arrived in the New World.The modern game of hockey emerged in England in the mid-18th century and is largely attributed to the growth of public schools, such as Eton.The first Hockey Association was formed in the UK in 1876 and drew up the first formal set of rules. The original association survived for just six years but, in 1886, it was revived by nine founding member clubs.However, the first version of modern-day field hockey was developed by the British sometime between the late 18th and early 19th century.It was introduced as a popular school game then and made its way to the Indian army during British rule in the 1850s.The availability of large plots of land as playing fields and the uncomplicated nature of equipment meant that hockeygradually became the popular sport of choice among children and young adults in India, with the country's first hockey club being formed in then Calcutta (now Kolkata) in 1855.In the next few decades, national competitions like the Beighton Cup in Calcutta and Aga Khan tournament in Bombay (now Mumbai) popularised the sport further, especially in erstwhile provinces of Bombay and Punjab.There were talks of forming a hockey association in India in 1907 and 1908, but it didn't materialise. The Indian Hockey Federation (IHF) was only formed in 1925, one year after the formation of the International Hockey Federation (FIH).The IHF organised its first international tour in 1926 to New Zealand, where the Indian hockey men's team played 21 matches and won 18. The tournament saw the emergence of a young Dhyan Chand, who would go on to become arguably the best layer the world has ever seen. After a rocky relationship with the Olympic Games until 1924 -- hockey was only played in 1908 and 1920 and dropped forthe other editions -- the presence of a global sports body (FIH) ensured that hockey gained permanent Olympic statusstarting Amsterdam 1928.The Indian Hockey Federation applied and earned an FIH membership in 1927, thus ensuring that the Indian hockey team would play its first Olympics in 1928.It was the beginning of a legacy - decorated with eight gold medals - a record till today.Hockey is a national game of india.Major Dhyan Chand is considered one of the best hockey players of all time. He had an extraordinary talent for scoring goals, due to which India won hockey gold medals in the Olympic Games of 1928, 1932, and 1936.His era is called the GOLDEN PERIOD of Indian hockey.He is called the HOCKEY WIZARD due to his excellent control over the ball. Major Dhyan Chand announced his retirement from hockey in the year 1948. He had scored more than 400 goals in his international career.The Government of India awarded him the Padma Bhushan, the third-highest civilian honour, in the year 1956. His birthdayis celebrated as National Sports Day in India on 29 August and several awards are presented by the President on this day.Hockey magician Dhyan Chand's autobiography titled GOAL was published in 1952."
    ],
    "Rules": [
      "Rules:-",
      "1. You may only use the flat side of your stick.",
      "2. You must be properly attired – shin guards, mouth guards, no jewelry, etc.",
      "3. 10 field players plus a goalie play at one time.",
      "4. The field hockey game lasts for two 30 minute halves.",
      "5. Substitutions – the field player must exit the field at the 50, only then can the new player step onto the field.",
      "6. The ball cannot go in the air, especially on free hits. This is judged by the discretion of the ref. The exception is a shot on goal, as long as there is not a player in the direct line of the ball and no one is in harm’s way.",
      "7. Self –start. When taking a hit into the circle, whether it is a free hit or long hit, you cannot directly hit into the circle. You must pass it first or carry the ball for 5 yards before hitting the ball into the circle.",
      "For free hits anywhere else on the field, you may either: take a direct hit, pass to one of your players, or carry the ball for 3 yards before hitting it.",
      "8. Any time a foul occurs in either team’s circle, a corner hit will be called.",
     "Fouls:-",
      "1. The ball cannot hit your feet.",
      "2. You cannot raise your stick above your waste during regular play. If you are taking a free hit, it is up to the discretion of the ref.",
      "3. You cannot tackle (go for the ball) from behind. You must face your opponent head on (shoulder to shoulder) if you are fighting for the ball.",
      "4. No third party. It is one vs. one at all times. Once another player tries to go for the ball, a foul is called.",
      "5. Obstruction  when your back is turned to another player and you are between the ball and that player."
    ],
    "Supplements": [
      "Supplements:-",
      "1. Protein Powder .Why is this important for hockey players? – Once you get in season, preserving muscle is key. Many pro players can lose 10 or more pounds during the season and its not just fat. Hitting your protein targets is paramount!",
      "2. Caffeine Why is this important for hockey players? – Caffeine is a highly studied supplement and as long as you have no pre-existing heart or blood pressure issues, is well tolerated by the majority of the population!",
      "3. Creatine Why is Creatine important for hockey players? Production of ATP for faster muscles with more endurance is nothing but a positive for your game. This is a very cheap, effective supplement that will help you day in and out!",
      "4. Beta Alanine Why is Beta Alanine important for hockey players? Feeling that lactic acid build up when you are caught out on a long shift is a terrible feeling, physically and mentally. Buffer the effects of lactic acid and get another gear for your game by using Beta Alanine!",
      "5. Vitamin D Why is Vitamin D important for hockey players? Vitamin D is one of the most important supplements you can take for your health and longevity. I’ve had low Vitamin D levels before and felt like complete crap. Make sure to get tested oftenand keep your levels on the upper site of optimum!",
      "6. Fish Oil / Omega 3 Fatty Acids Why is Fish Oil important for hockey players? Keeping your brain in top health, your inflammation low, and improving heart health will all keep you going bar down game in and game out!",
      "7. Magnesium Why is Magnesium important for hockey players? Other than being responsible for over 325 enzymatic processes in the body, it is crucial for ATP production which is paramount during bouts of intense exercise!"
    ],
    "Awards_Honours": [
      "Awards and Honours:-",
      "Major Dhyan Chand Lifetime Achievement Award – Rs.30,00,000/-",
      "Dhruv Batra Award Player of the Year (Men) – Rs.25,00,000/-",
      "Dhruv Batra Award Player of the Year (Women) – Rs.25,00,000/-",
      "Jugraj Singh Award for Upcoming Player of the Year (Men – Under 21) – Rs.10,00,000/-",
      "Asunta Lakra Award for Upcoming Player of the Year (Women – Under 21) – Rs.10,00,000/-",
      "Baljit Singh Award for Goalkeeper of the Year – Rs.5,00,000/-",
      "Pargat Singh Award for Defender of the Year – Rs.5,00,000/-",
      "Ajit Pal Singh Award for Midfielder of the Year – Rs.5,00,000/-",
      "Dhanraj Pillay Award for Forward of the Year – Rs.5,00,000/-",
      "Jaman Lal Sharma Award for Invaluable Contribution – Rs.5,00,000/-",
      "Hockey India President Award for Outstanding Achievement – Rs.5,00,000/-"
    ]
  },
  {
    "id": 2,
    "Sport_Name": "Table-tennis",
    "History": [
      "History:-",
      "Table tennis made its Olympic debut at the Seoul 1988 Games with men's and women's singles and doubles.Table tennis has come a long way from its late 19th century origins as an after-dinner game played by upper-class English families.Legend has it that the first players used the lids of cigar boxes for rackets and a rounded-off cork from a champagne bottle as the ballOld-fashioned names for table tennis include 'ping pong', 'whiff waff' and 'flim flam'.In 1980 the first World Cup was held, and Guo Yuehua of China won the $12,500 first prize.first player to play table tennis from india was Achanta Sharath Kamal. he is an Indian professional table tennis player. He is the first Indian table tennis player ever to become nine times Senior National Champion hence breaking the record of eight times National Champion Kamlesh Mehta."
    ],
    "Rules": [
      "Rules:-",
      "1.GAMES ARE PLAYED TO 11 POINTS:-A Game is played to 11 points. A Game must be won by two points. A Match is generally the best three of five Games",
      "2.ALTERNATE SERVES EVERY TWO POINTS:- Each side of the table alternates serving two points at a time. EXCEPTION: After tied 10-10 (“deuce”), service alternates at every point. Can you lose on a serve in ping pong? Yes! There is no separate rule for serving on Game Point",
      "3.TOSS THE BALL STRAIGHT UP WHEN SERVING:- How do you serve the ball in ping pong? Hold the ball in your open palm, behind your end of the table. Toss at least 6” straight up, and strike it on the way down. It must hit your side of the table and then the other side. NOTE: Once the ball leaves the server’s hand it is in play, and so counts as the receiver’s point if the ball is missed or mis-hit",
      "4.THE SERVE CAN LAND ANYWHERE IN SINGLES:- There is no restriction on where the ball lands on your side or your opponent’s side of the table. It can bounce two or more times on your opponent’s side (if so, that’s your point), bounce over the side, or even hit the edge",
      "5.DOUBLES SERVES MUST GO RIGHT COURT TO RIGHT COURT:- The serve must bounce in the server’s right court, and receiver’s right court (NOTE: landing on center line is fair). Doubles partners switch places after their team serves twice",
      "6.A SERVE THAT TOUCHES THE NET ON THE WAY OVER IS A “LET”:- Can the ball hit the net in ping pong? Yes, during a RALLY, if it touches the top of the net and then otherwise lands as a legitimate hit. BUT not when serving. If a served ball hits the net on the way over and otherwise legally bounces in play, it’s a “let” serve and is done over. There is no limit on how many times this can happen",
      "7.ALTERNATE HITTING IN A DOUBLES RALLY:- Doubles partners must alternate hitting balls in a rally, no matter where the ball lands on the table",
      "8.VOLLEYS ARE NOT ALLOWED:- Can you hit the ball before it bounces in ping pong? No. In regular tennis you may “volley” the ball (hitting the ball before it bounces on your side of the net). But in table tennis, this results in a point for your opponent. NOTE: When your opponent hits a ball that sails over your end of the table without touching it and then hits you or your paddle, that is still your point",
      "9.IF YOUR HIT BOUNCES BACK OVER THE NET BY ITSELF IT IS YOUR POINT If:- you hit the ball in a rally or on a serve and it bounces back over the net after hitting your opponent’s side of the table (due to extreme spin), without your opponent touching it, that is your point",
      "10.TOUCHING THE BALL WITH YOUR PADDLE HAND IS ALLOWED:- What happens if the ball hits your finger or hand during a ping pong rally?  If the ball touches your PADDLE hand and otherwise results in a legal hit, there is no rule violation and play shall continue as normal. Your paddle hand includes all fingers and hand area below the wrist. But what if the ball touches a player’s body anywhere else during a ping pong rally? You may not touch the ball with your non-paddle hand for any reason. It will result in a point for your opponent. BUT if  your opponent’s hit sails over your side of the table without touching it, and hits any part of you or your paddle, that is still your point",
      "11.YOU MAY NOT TOUCH THE TABLE WITH YOUR NON-PADDLE HAND:- You may touch the ball or the table with your paddle hand (after reaching in to return a short serve, for example), or other parts of your body. NOTE: If the table moves at all from your touching it during a rally, that is your opponent’s point",
      "12.AN “EDGE” BALL BOUNCING OFF THE HORIZONTAL TABLE TOP SURFACE IS GOOD:- An otherwise legal serve or hit may contact the top edge of the horizontal table top surface and be counted as valid, even if it bounces sidewise. The vertical sides of the table are NOT part of the legal playing surface",
      "13.HONOR SYSTEM APPLIES TO DISAGREEMENTS:- If no referee is present during a match and the players disagree on a certain call, the “honor system” applies and the players should find a way to agree, or play the point over. Ping pong carries a tradition of fierce but fair play. Help us keep it that way",
      "14.Table tennis equipment is relatively simple and inexpensive. The table is rectangular, 9 feet by 5 feet (2.7 metres by 1.5 metres), its upper surface a level plane 30 inches (76 cm) above the floor. The net is 6 feet (1.8 metres) long, and its upper edge along the whole length is 6 inches (15.25 cm) above the playing surface. The ball, which is spherical and hollow, was once made of white celluloid. Since 1969 a plastic similar to celluloid has been used. The ball, which may be coloured white, yellow, or orange, weighs about 0.09 ounce (2.7 grams) and has a diameter of about 1.6 inches (4 cm). The blade of a racket, or bat, is usually made of wood, is flat and rigid, and may be covered with a thin layer of ordinary stippled, or pimpled, rubber, which may be laid over a thin layer of sponge rubber and may have the pimples reversed. Whatever combination is used, each of the two sides of a paddle must be different in colour. The racket may be any size, weight, or shape"
    ],
    "Supplements": [
      "Supplements:-",
      "1. Enjoy a variety of foods",
      "2. Emphasize cereals, grain products, fruits and vegetables",
      "3. Choose low-fat dairy products, lean meat and food prepared with little or no fat",
      "4. Perform regular physical activity to achieve and maintain a healthy body weight",
      "5. Limit the intake of salt, alcohol and caffeine.",
      "Food to Avoid:-",
      " 1.Fatty foods, because they are slow to digest",
      "2. Protein-rich food, because they are slow to digest and are not needed as fuel during exercise",
      "3. Alcoholic beverages such as wine, and beer, because they can have a dehydrating effect",
      "4.Spicy foods may be difficult to digest prior to exertion. (When traveling in other countries, athletes can bring a few favorite spices if they are already used to them.) ",
      "5. Gas-producing foods like cabbage, broccoli, onions, and carbonated drinks, make some athletes feel bloated. Coffee, tea, cola, and chocolate may cause diarrhea, which can have a dehydrating effect."
    ],
    "Awards_Honours": [
      "Awards and Honours:-",
      "The ITTF Star Awards is the official awards ceremony organised by the International Table Tennis Federation since 2013. It is the most prestigious award given to recognize, honor and celebrate the STARS of table tennis, the athletes who have made table tennis their passion, career and life.also given dronacharya award and arjuna award",
      "1. Manika Batra became the first Indian to win a 'Breakthrough Table Tennis Star' award at the prestigious ITTF Star Awards in South Korea on Wednesday",
      "2. The 2019 Dronacharya Award for Table Tennis was given to Sandip Gupta",
      "3. the arjuna award winner in 2020 was Ms Madhurika Suhas Patka",
      "4. the arjuna award winner in 2019 was harmeet desai",
      "5. the arjuna award winner in 2018 was Manika Batra and Sathiyan Gnanasekaran"
    ]
  },
  {
    "id": 3,
    "Sport_Name": "Badminton",
    "History": [
      "History:-",
      "A game which has been derived, or its roots can be traced from ancient Greece,China but mainly in Poona,India where British army officers played and stationed in India in 1860's.A game that has completely changed the perspective of sports and games came into existence as a demonstration sport in 1972 and an exhibition sport in 1988.But, as we say, a good sport finds its way to the players,finally found its way in 1992 where it became a full medal olyampic sport,with competition for men's and women's singles (one against one) and doubles (two against two). Mixed doubles was introduced at the 1996 Games.Badminton was prominent in India but in olympics,it started it's journey right from the start i.e. 1992 which Deepankar Bhattacharya and Vimal kumsr represented India.BADMINTON is the national sport of Indonesia from both the participation and spectating aspect. It has won gold medals in badminton in every Olympic Games since 1992."
    ],
    "Rules": [
      "Rules:-",
      "1. A game starts with a coin toss. Whoever wins the toss gets to decide whether they would serve or receive first OR what side of the court they want to be on. The side losing the toss shall then exercise the remaining choice.",
      "2. At no time during the game should the player touch the net, with his racquet or his body.",
      "3. The shuttlecock should not be carried on or come to rest on the racquet.",
      "4. A player should not reach over the net to hit the shuttlecock.",
      "5. A serve must carry cross court (diagonally) to be valid.",
      "6. During the serve, a player should not touch any of the lines of the court, until the server strikes the shuttlecock. During the serve the shuttlecock should always be hit from below the waist.",
      "7. A point is added to a player's score as and when he wins a rally.",
      "8. A player wins a rally when he strikes the shuttlecock and it touches the floor of the opponent's side of the court or when the opponent commits a fault. The most common type of fault is when a player fails to hit the shuttlecock over the net or it lands outside the boundary of the court.",
      "Scoring System:-",
      "1. A match consists of the best of 3 games of 21 points.",
      "2. Every time there is a serve – there is a point scored.",
      "3. The side winning a rally adds a point to its score.",
      "4. At 20 all, the side which gains a 2 point lead first, wins that game.",
      "5. At 29 all, the side scoring the 30th point, wins that game.The side winning a game serves first in the next game."
    ],
    "Supplements": [
      "Supplements:-",
      "Badminton players need vitamins such as thiamine, riboflavin, niacin, and iron-like minerals to use the extra calories they need while playing. It is necessary to obtain these vitamins and minerals by including new fruits, vegetables, greens, eggs etc. in their diet.Some of the names",
      "1. Almonds – Enables Less Fatigue",
      "2.Banana – The Concentration Booster",
      "3. Salmon – Your Eyesight Turbo Engine",
      "4. Poultry Lean Meat – For Muscle Building",
      "5. Kale – Multi-Functional Booster",
      "6. Egg – Your Protein Source",
      "7. Dairy milk – Your Bones Strengthen Weapon"
    ],
    "Awards_Honours": [
      "Awards and Honours:-",
      "Rajiv Gandhi Khel Ratna",
      "Dhyan Chand Award",
      "Dronacharya Award"
    ]
  },
  {
        "id": 4,
        "Sport_Name": "Javelin-throw",
        "History": [
          "History:-",
          "Javelin Throw is a track & field (throwing) athletics event in which athletes try to throw a spear called Javelin farther from the opponents to win the competition. The javelin weighs around 800g and is 2.6-2.7m long for men and for women it is 2.2-2.3m long and weighs around 600g. The sport was evolved from the everyday use of the spear for hunting purposes. It was widely practiced in the Ancient Greece and became a part of the pentathlon of the Ancient Olympics in 708BC. The rules and the javelin continued to evolve over the decades and the sport became a part of the modern Olympics since 1908 for men and 1932 for women.Throwing the javelin as sport evolved from the everyday use of the spear in hunting and warfare. It was widely practised in Ancient Greece and incorporated into the Olympic Games in 708BC as part of the pentathlon. It has been part of the modern Olympic Games programme since 1908 for men and 1932 for women. In 1986 the men's javelin was redesigned; its centre of gravity was moved forward by four centimetres. This shortened throwing distances by approximately 10 per cent by bringing its nose down earlier and more steeply. This move was made because the men, following a world record of 104.80m by East Germany's Uwe Hohn in 1984, were in danger of throwing the javelin beyond the space available in normal stadiums. In 1999, the women's javelin was similarly redesigned.The Czech athlete Jan Zelezny is regarded as the finest make javelin thrower in history. He won a hat-trick of Olympic titles from 1992-2000 and set the world record of 98.48m in 1996. His compatriot Barbora Spotakova is among the leading female javelin throwers in history, she won successive Olympic titles in 2008 and 2012 and is the owner of the women’s world record with a best of 72.28m."
        ],
        "Rules": [
    "Rules:-",
    "Holding the javelin must be done at the grip part and should always be maintained above the shoulder level.",
    "For valid throw, the javelin must lie before the specified zone and its tip should hit the ground.",
    "There is a special marking line on the runway within which the athlete needs to throw.",
    "The athlete should not leave the ground until the javelin lands on the ground.",
    "After the throwing action has been made, the thrower should not turn back towards the pointing direction, until it lands.",
    "The number of throws allowed per athlete is same as that of the discus throw.",
    "Once the competition has started, the athletes cannot use the perimeter for practise purpose.",
    "Using any device that may assist the thrower in throwing is strictly prohibited. For example, tapping of fingers are not allowed unless there is a wound.",
    "The throw will be considered as a foul in the following cases −",
    "Improper throw of the javelin in the attempt.",
    "Demarking of the line with any body part.",
    "Player going out of the marking line while throwing.",
    "The tip of the javelin lies outside the edges of the landing sector.",
    "The time is increased to 1 minute if there are 2-3 number of competitors.In case only one competitor is left, time is increased to 2 minutes."
        ],
       "Supplements": [
         "Supplements:-",
         "1.Caffeine:-This one is the best. It doesn’t matter if you are a thrower, jumper, football player, wrestler, or distance runner. There is no legal supplement out there with a more powerful effect than caffeine. There is a reason 83% of Americans drink at least a cup of coffee in the morning. Caffeine gives you a strong burst of energy that lasts 45 min to an hour. It will get you pumped up to hit a huge PR, give you more pop in your throw, and focus your mind to execute better technique. I absolutely believe that taking caffeine can add 2 feet to your throw if you are a shot putter.",
    "Advantages:-", 
    "1.Most scientifically proven ergogenic aid that is legal",
    "2.Very cheap and easy to take anywhere",
    "3.Quick onset time ~15 minutes",
    "Disadvantages:-",
    "1.Can give inexperienced athletes more jitters",
    "2.May cause you to rush or tighten up in your technique",
    "3.The maximum legal dose is the equivalent of 7 cups of coffee",
    "How to take:-",
    "Consume by either drinking coffee, pre-workout, or caffeine pills. There is an approximate 15 minute time period for the caffeine to be absorbed. During competitions I like to take it just before I step in the circle for my first warm up throw. Note that caffeine is absorbed more quickly through the salivary glands in your mouth, so swishing it in your mouth or chewing caffeine gum will increase the absorption time.", 
    
    "2.Creatine. Although caffeine has a great effect, most people see supplements as something you use for longer term adaptation aids. This is where creatine sits at the top. Again... creatine is not a steroid. Your body produces it naturally and it is consumed in small quantities in meat. However, supplementing creatine is proven to increase the training capacity of short bursts of work, increase force production, and develop long-term hypertrophy. I know everyone likes to try and kill creatine by saying it’s just water weight, but although the initial weight gain is from an increase of water in the tissue, research has found that over 2-3 months the training effect of creatine replaces that mass with dry tissue. Be aware however, that the average weight gain is 2 kilos during the first week of supplementation.", 
    "Advantages:-",
    "1.Increases your endurance on 5x5 sets",
    "2.Develops greater force production on throws",
    "3.Handle heavier shots more easily",
    "4.Gains weight (if you need to gain weight)",
    "5.Not too pricy, and one container lasts a long time",
    "Disadvantages:-",
    "1.Gains weight (if you are trying to lose weight)",
    "2.Requires very consistent usage", 
    "How to Take",
    "There are a number of different loading schemes, but this one is research proven and we have found to work well. During the first 4 days, take 10 grams (two loaded scoops) 4 times per day. After that take 4 grams (one scoop) once per day. Try to take your creatine at the same time each day. You can mix it with water, juice, or your protein. Some of our athletes just dump the scoop right in their mouth, then wash it down with water. It has no taste but is a little gritty. It may be useful to cycle creatine twice per year, taking a month or two off. Some like the feeling of getting back on to break a plateau or just to feel the difference creatine makes again. However, there is no research to say that the effects of creatine will wear off if you don’t cycle it.",
    
    "3.Whey Protein:-Whey is by far the most popular supplement on the market. This is the first supplement I would say you can get by without if everything in your diet is top notch. Throwers who are training hard need 200+ grams of protein per day. This can be achieved by eating meat, dairy products, beans, etc. However, unless you are tracking everything you are eating you won’t know for sure if you are getting enough. I find whey great as a consistent source of protein to always make sure that my tissue has what it needs to fully repair after training. I should also note that your kidneys will NOT fail if you eat too much protein. If you are trying to lose weight however, it is still okay to take protein, but just make sure that it is a replacement for 250 calories elsewhere in your diet.",
    "Advantages:-",
    "1.Great mass gainer",
    "2.A consistent source of quality protein",
    "3.Endless creative ways to take it",
    "Disadvantages:-",
    "1.Extra calories (if you are trying to lose weight)",
    "2.A little pricy if you are drinking 2+ shakes a day",
    "How to take:-",
    "For the typical thrower who is trying to keep muscle mass maxed out and weight high, a shake in the morning and post-workout is best. If you are really trying to pack on the pounds, you can take it pre-workout and before bed as well. It can be fun to be creative with how you eat your protein. It tastes great simply taking it with milk, but you can try it in a smoothy, pancakes, cookies, or oatmeal as well. If you are trying to lose or maintain weight, it is best to mix it with water." 
        ],
        "Awards_Honours": [
         "Awards and Honours:-",
         "Arjuna Award",
         "Vishisht Seva Medal (VSM)",
         "Major Dhyan Chand Khel Ratna Award – 2021 (highest sporting honour of India)"
        ]
      },
      {
        "id": 5,
        "Sport_Name": "Volleyball",
        "History": [
          "History:-",
          "The sport of volleyball originated in the United States, and is now just beginning to achieve the type of popularity in the U.S. that it has received on a global basis, where it ranks behind only soccer among participation sports.In 1895, William G. Morgan, an instructor at the Young Men’s Christian Association (YMCA) in Holyoke, Mass., decided to blend elements of basketball, baseball, tennis, and handball to create a game for his classes of businessmen which would demand less physical contact than basketball. He created the game of Volleyball (at that time called mintonette).Per Morgan, the game was fit for the gymnasium or exercise hall but, could also be played outdoor. The play consisted of any number of players keeping a ball in motion from one side to the other over a net raised 6 feet 6 inches above the floor. Play is started by a player on one side serving the ball over the net into the opponents’ field or court. The opponents then, without letting the ball strike the floor, return it, and it is in this way kept going back and forth until one side fails to return the ball or the ball hits the floor. The side serving the ball earns points when the opposite side either fails to return the ball or allows the ball to hit the floor.During a demonstration game, someone remarked to Morgan that the players seemed to be volleying the ball back and forth over the net, and perhaps “volleyball” would be a more descriptive name for the sport."
        ],
        "Rules": [
          "Rules:-",
          "The objective in volleyball is to keep the ball from striking the floor on your side of the net and return it so that it strikes the floor on your opponent’s side, before they can return it.",
          "Play:",
          "1.The ball is put into play by the right back position (1) from behind the rear boundary line using either an underhand or overhand serve.",
          "2.The serve must go over the net within the court boundaries on the other side. A serve that hits the net and still goes over to the other side is a good serve and referred to as a let serve.",
          "3.The ball can only be played with 3 touches, per team, per play, and then must be sent over the net. The ball can go over the net with less then 3 touches without penalty.",
          "4.The ball may not be hit 2 times in a row by any one player.",
          "5.Only front row players are allowed to contact the ball above the net with intention to attack. However, a back row player may attack the ball upon the net if they are behind the 10 feet line.",
          "6.If the serving team loses the serve (ball lands on their own side or ball is hit out of bounds), the other team obtains service and a point. This is called a side out/point.",
          "7.A ball that lands on the boundary line is considered in.",
          "8.For every side out made, the team that is awarded the serve must rotate in a clockwise manner.",
          "9.If the ball hits the ceiling and goes over the net, it is a dead ball. If the ball hits the ceiling and falls back onto the original side, it is playable if there are still hits available.",
          "10.In rally scoring, a point is awarded at the end of every play no matter who is serving.",
          "11.Each game is played to 25 points and the winning team must win by at least 2 points.",
          "12.The match is a best of 5 contest.",
          "Court and Equipment:-",
          "1.The court is 60 ft. long and 30 ft. wide",
          "2.The boundary lines are 2 inches wide.",
          "3.A 4 inch line divides the court at 30 ft.",
          "4.A men’s net is 8 ft. high.",
          "5.A women’s net is 7 ft. 4 1/8 inches.",
          "Court Positions:-",
          "Right back",
          "Center back",
          "Left back",
          "Left front",
          "Center front",
          "Right front",
          "Volleyball Terminology:-",
          "1.Block: Defensive play by the player(s) in the front row who place their hands and arms above the net so that a spiked ball rebounds into the opponents court.",
          "2.Pass: The forearm pass made on balls below the waist.",
          "3.Game Point: The last point in any game.",
          "4.Set: The overhead pass using the fingertips of an open hand.",
          "5.Rotation: The shifting of players, clockwise, just before a new person serves.",
          "6.Attack: An approach to the net, a vertical jump, and a forceful hit of the ball down onto the opponent’s court.",
          "7.Touch: When a player attempts to block the ball unsuccessfully and it continues onto their own side of the court. This does not count as one of the 3 hits allowed per side.",
          "8.Tip: Attempting to trick the defense by dumping the ball right over the net.",
          "9.Defensive specialist (DS): A player who only plays in the back row.",
          "10.Libero: A DS that wears a different color jersey from the rest of the team that can enter the back row ONLY for any player throughout the game.This does not count against the teams substitution count.",
          "11.Substitution: At a dead ball opportunity, the coach signals the referee that he/she would like to make a player change. In volleyball, once a player subs in for another player, they cannot return in the game for a different player. A total of 18 substitutions are allowed per game."
        ],
        "Supplements": [
          "Supplements:-",
          "1.MULTIVITAMIN:-Multivitamins provide a range of vitamins and minerals essential for the body’s daily activities. Few people consume the right amount of all essential vitamins and minerals through their regular diets, which makes multivitamins even more important. Proper intake of these nutrients increases endurance, energy and aerobic capacity and improves recovery.",
          "2.FLAXSEED OIL:-Flaxseed oil is a great source of omega-3 fatty acids (O-3FA)—an essential fat. Because the body cannot produce it, O-3FA must be consumed through diet or supplementation. Adequate O-3FA intake speeds recovery and reduces muscle inflammation after workouts and competition. It also improves cardiovascular function and overall health. Some studies have linked O-3FA with increased strength levels, but further research is necessary.",
          "3.VITAMIN C:-Few things negatively affect performance more than illness and disease, so a healthy immune system is essential. Vitamin C is great for boosting the immune system and overall health. It also improves endurance and aerobic capacity and helps repair connective tissue—a major benefit for strength-training athletes.",
          "4.PROTEIN SHAKE:-Protein is vital for repairing muscles after they’ve broken down from intense exercise or competition. The amino acids in protein are the body’s building blocks for making muscles bigger and stronger. Without adequate protein intake, this process cannot occur. Protein shakes supply protein without significant amounts of fat or calories—an added benefit to athletes concerned about fat loss."
        ],
        "Awards_Honours": [
          "Awards and Honours:-",
          "Volleyball Centennial Cup",
          "Federation Cup",
          "Indira Pradhan Trophy",
          "Shivanthi Gold Cup",
          "World League Cup.",
          "OVA(Ontario Volleyball Association)Awards",
          "Arjuna Award"
        ]
      },
      {
        "id": 6,
        "Sport_Name": "Lawn-tennis",
        "History": [
          "History:-",
          "Origin and early years. There has been much dispute over the invention of modern tennis, but the officially recognized centennial of the game in 1973 commemorated its introduction by Major Walter Clopton Wingfield in 1873.",
          "Most historians believe that tennis was originated in the monastic cloisters in northern France in the 12th century, but the ball was then struck with the palm of the hand; hence, the name jeu de paume (game of the palm).",
          "There has been much dispute over the invention of modern tennis, but the officially recognized centennial of the game in 1973 commemorated its introduction by Major Walter Clopton Wingfield in 1873. He published the first book of rules that year and took out a patent on his game in 1874, although historians have concluded that similar games were played earlier and that the first tennis club was established by the Englishman Harry Gem and several associates in Leamington in 1872. Wingfield’s court was of the hourglass shape and may have developed from badminton. The hourglass shape, stipulated by Wingfield in his booklet Sphairistiké, or Lawn Tennis, may have been adopted for patent reasons since it distinguished the court from ordinary rectangular courts. At the time, the Marylebone Cricket Club (MCC) was the governing body of real tennis, whose rules it had recently revised. After J.M. Heathcote, a distinguished real tennis player, developed a better tennis ball of rubber covered with white flannel, the MCC in 1875 established a new, standardized set of rules for tennis.",
          "Meanwhile, the game had spread to the United States in the 1870s. Mary Outerbridge of New York has been credited with bringing a set of rackets and balls to her brother, a director of the Staten Island Cricket and Baseball Club. But research has shown that William Appleton of Nahant, Massachusetts, may have owned the first lawn tennis set and that his friends James Dwight and Fred R. Sears popularized the game.",
          "An important milestone in the history of tennis was the decision of the All England Croquet Club to set aside one of its lawns at Wimbledon for tennis, which soon proved so popular that the club changed its name to the All England Croquet and Lawn Tennis Club. In 1877 the club decided to hold a tennis championship, and a championship subcommittee of three was appointed. It decided on a rectangular court 78 feet (23.8 metres) long by 27 feet (8.2 metres) wide. They adapted the real tennis method of scoring—15, 30, 40, game—and allowed the server one fault (i.e., two chances to deliver a proper service on each point). These major decisions remain part of the modern rules. Twenty-two entries were received, and the first winner of the Wimbledon Championships was Spencer Gore. In 1878 the Scottish Championships were held, followed in 1879 by the Irish Championships.",
          "The dominant champions of the early postwar years were Bill Tilden of the United States and Suzanne Lenglen of France. Tilden, the U.S. champion from 1920 through 1925 and again in 1929, won the Wimbledon title in 1920, 1921, and 1930. In the same period he also won 15 Davis Cup singles. Suzanne Lenglen reigned supreme over the ladies’ game from 1919 to 1925; were it not for the war, she might have started her international career earlier. She won the Wimbledon championship at her first attempt in 1919, from 1920 to 1923, and in 1925, not competing in 1924 because of illness. She developed a powerful as well as accurate game by practicing with men, and she needed far more freedom of movement than restrictive ladies’ fashion of that time allowed. Her first appearance at Wimbledon in a calf-length white dress with short sleeves and without petticoat or suspender (garter) belt caused a sensation."
        ],
        "Rules": [
          "Rules:-",
          "i.General rules of tennis:-",
          "1.A ball must land within bounds for play to continue; if a player hits the ball outside of bounds, this results in the loss of the point for them.",
          "2.Players/teams cannot touch the net or posts or cross onto the opponent’s side.",
          "3.Players/teams cannot carry the ball or catch it with the racquet.",
          "4.Players cannot hit the ball twice.",
          "5.Players must wait until the ball passes the net before they can return it.",
          "6.A player that does not return a live ball before it bounces twice loses the point.",
          "7.If the ball hits or touches the players, that counts as a penalty.",
          "8.If the racquet leaves the hand or verbal abuse occurs, a penalty is given.",
          "9.Any ball that bounces on the lines of boundary are considered good.",
          "10.A serve must bounce first before the receiving player can return it.",
          "ii.Equipments:-",
          "1.Racquet :-A racquet is comprised of a handle, a frame, and strings that are bound in a crisscross weaving pattern. A racquet’s frame should not exceed 32 inches in length, with a handle no longer than 12.5 inches in width, and a surface no more than 15.5 inches in overall length or 11.5 inches in width. There can also be no objects or devices on the racquet except for ones that prevent vibration and wear and tear.",
          "2.Ball:-A tennis ball is white or yellow in color for tournaments, with measurements of 2-1/2 to 2-5/8 inches in diameter and weighing anywhere from 2 to 2-1/16 ounces. The elasticity of the ball and the uniform outer surface are also determined by approved specifications.",
          "iii.Scoring:-",
          "1.Points:-Smallest unit of measurement. Points increment from Love(0)-15-30-40-game.",
          "2.Games :–Games consist of 4 points each, and is won when a player reaches 4 points with at least a 2 point advantage.",
          "3.Sets :–A set consists of 6 games and is won by the player/team who reaches 6 games first with least a 2 point lead.",
          "4.Advantage Set :–If a game score of 6-6 is reached and advantage set rules are used, a player/team can only win a set with a 2 game lead.",
          "5.Matches :–A match is usually played as best of 3 or best of 5 sets.",
          "6.Deuce:–Occurs if a score of 40-40 is reached. In order to win the game, a player/team must win 2 consecutive points in order to take the game. If a player wins one point, they have advantage, but if they lose the next point, the score returns to deuce.",
          "7.Tie-break game :–If a game score of 6-6 is reached and tie-break set rules are used, players must play a tie-break game in order to decide who wins the set. In a tie-break game, a player/team must reach 7 points with a two point advantage to win. For the serving format of a tie-break game, player 1 serves for the first point, player 2 serves for the next two points, player 1 serves for the next two points after that, etc.",
          "iv.Serving and Choosing Sides:-",
          "1.Foot Fault:–A foot fault is when a player steps into the court or crosses the center mark before they have made contact with the ball. This results in the loss of the serve.",
          "2.Proper Serve:–A player serves on the right side of the court at the beginning of each game, with the goal of serving the ball into the diagonal service box. If the serve lands in the correct service box, play can continue. The server switches to serve on the left side for the next point, and vice versa until the game is over.",
          "3.First Service :–The server is allowed two chances to land their ball into the service box. The first attempt is known as the first service. Failing the first service leads to the second service.",
          "4.Second Service:–The second attempt is known as the second service. Failing the second service results in the loss of the point.",
          "5.Let :–A let is a re-do given to a player who serves although the ball hits the net cord before falling into the correct service box. You are allowed an infinite amount of lets, although it does not happen often.",
          "6.Order of Service:–The player/team who wins the toss serves first (team that wins chooses which player serves). If playing singles matches, players alternate between serving and receiving every game. If playing doubles matches, teams alternate between serving and receiving every game, with each player on a team getting the chance to serve before the cycle repeats.",
          "7.Switching Sides:–Players/teams switch sides for every odd-numbered game (so, games 3, 5, 7 etc.)",
          "v.Singles Vs. Doubles Tennis Rules:-",
          "Singles Tennis Rules:-",
          "Court Size:-A singles court uses the innermost sideline and measures a total of 27 feet wide by 78 feet long.",
          "Serving Order:-The player who wins the toss chooses who serves first. Whomever is serving first serves for the entire duration of the first game. After the game, the next server will be the player who received last, serving for the duration of the second game. For every odd-numbered game, players switch sides of the court.",
          "Tie-Break Serving Order:-If a score of 6-6 is reached and tie-break rules are used, a tie-break game is played in order to determine which player wins the set. For a tie-break game, the goal is to reach 7 points first with a lead of at least 2, and doing so results in the win of the set. The player who serves first is the player who would normally serve after 6-6, or 12 games.",
          "Match format:-A singles match is often played to the best of 3 sets, although some mens singles tournaments play to the best of 5. It really all depends on the preferences of the players on the rules of the tournament.",
          "Doubles Tennis Rules:-",
          "Court Size:-A doubles court uses the outermost sideline and measures a total of 36 feet wide by 78 feet long.",
          "Serving Order:-The team who wins the toss chooses which team serves first, and that team will choose which of them will serve first. Whoever is serving first serves for the entire duration of the first game. After the game, the next server will be chosen by that team and will serve for the duration of the second game. For every odd-numbered game, teams switch sides of the court, and the player who hasn’t served yet from the first game must now serve, and the player who hasn’t served yet from the second team serves afterward, and so on.",
          "Match format:-A doubles match is often played to the best of 5 sets."
        ],
        "Supplements": [
          "Supplements:-",
          "SOME BASIC TIPS ON NUTRITION:-",
          "Do not starve muscles for fuel:-You should eat at least 5- 8 meals a day from complex carbohydrate choices which will help to create the base to maintain required muscles glycogen levels. Choose food with higher fibre options whenever possible such as cereals, bread, pasta etc.",
          "Never skip your breakfast:-Skipping the breakfast could decrease the energy level required for the game. As after the nine to twelve hour overnight fast your muscle energy levels are low and it will be unfair to expect yourself to perform at a peak without refuelling with carbohydrate sources.  So never skip a breakfast.",
          "Provide required protein (muscle building blocks) to your body:-Protein contain amino acids which are required to repair and rebuild the muscle building blocks make muscle more stronger to perform better. Muscle strength increases the power to play with high intensity for every shot during the game. MFF Whey protein 80™ which is a dairy source protein will help to complete the required protein diet for your body.",
          "High vitamin and mineral nutrition:-Consuming the food with high vitamins and minerals will help your body to recover and perform better over the period of time. Vitamins and minerals plays an important role in refuelling and increasing absorption of different other nutrients required by the body.",
          "Drink lot of water:-As tennis is a game which could last from an hour up to an excess of five hours, so the important to stay hydrated is very important. Dehydration with not only affect the decision making but will also decrease the speed and endurance of the body.",
          "Proper sleep:-Recovery isn't just about nutrition, but keeping nutrition aside, sleep is super important. A proper 8 -10 hours of sleep is a must for players to deliver their best performance.",
          " IMPORTANT FITNESS TRAINING TIPS FOR BETTER PERFORMANCE:-",
          " Muscle Fitness:-Large muscles help to generate speed and it’s important that you be able to use the muscle at maximum intensity during the multi hour tennis match. During your season or as you get closer to it, focus on muscular endurance, reactive power and explosive power rather than bodybuilding.",
          "Muscle Training:-Perform circuit training workouts for muscular endurance. You can use barbells to do exercises such as biceps curls, triceps extension, squats, lunges, chest press and deadlifts. Use 50 percent of your maximum weight and perform atleast 10 reps of an exercise. Take one minute brake, then start a new exercise.So as to improve the explosive power, perform deadlifts, box squats, and one leg and split-squat jumps. To improve your ability to coordinate two movements like the downward knee and push upward on a serve, perform ankle jumps, skipping, giant steps, shock jump and sprints.",
          "Avoid long moderate Aerobic exercises:-Long and moderate intensity runs uses low twitch muscle fibres and train your aerobic system. In tennis you have to move fast during a tennis point, train fast which is opposite to the long and moderate intensity aerobic runs. Train your muscles for long or the short run. Sprint train using 300 to 90- second, high intensity movements, then rest three times as long as you worked to allow your body to get into the rhythm of tennis match. This kind of training will help you train your ability to recover after point and make you ready for next quick movement.",
          "Footwork:-You have to move in several direction during a tennis match so it important to have good training done on footwork. Perform footwork drills that have you move forward, at an angle, side to side and backward and forward. Practice running to one side, then recovering to the centre of court with different footwork, such as crossover step and shuffle steps. It is also important to keep your feet in contact with the ground for as little time as possible during footwork drills.",
          "Stretching:-According to researchers of Kansas state university, don’t static stretch before matches and workouts as it can decrease your power and vertical leap for upto 30 minutes after stretch. After a five minutes hitting warm-up, perform dynamic stretches, such as high-knee skipping, racket swings and jumping jacks. Static stretching helps tennis players improve flexibility, and you should stretch this way after each workout and match."
        ],
        "Awards_Honours": [
          "Awards and Honours:-",
          "Davis Cup(International Lawn Tennis Challenge Trophy)",
          "World Champions Dinner",
          "ATP World Tour Awards",
          "Golden Bagel Award",
          "International Tennis Hall of Fame",
          "ITF World Champions",
          "Venus Rosewater Dish"
        ]
      },
      {
        "id":7,
        "Sport_Name": "Swimming",
        "History": [
          "History:-",
          "Swimming, in recreation and sports, the propulsion of the body through water by combined arm and leg motions and the natural flotation of the body. Swimming as an exercise is popular as an all-around body developer and is particularly useful in therapy and as exercise for physically handicapped persons. It is also taught for lifesaving purposes. For activities that involve swimming, see also diving, lifesaving, surfing, synchronized swimming, underwater diving, and water polo.",
          "Archaeological and other evidence shows swimming to have been practiced as early as 2500 BCE in Egypt and thereafter in Assyrian, Greek, and Roman civilizations. In Greece and Rome swimming was a part of martial training and was, with the alphabet, also part of elementary education for males. In the Orient swimming dates back at least to the 1st century BCE, there being some evidence of swimming races then in Japan. By the 17th century an imperial edict had made the teaching of swimming compulsory in the schools. Organized swimming events were held in the 19th century before Japan was opened to the Western world. Among the preliterate maritime peoples of the Pacific, swimming was evidently learned by children about the time they walked, or even before. Among the ancient Greeks there is note of occasional races, and a famous boxer swam as part of his training. The Romans built swimming pools, distinct from their baths. In the 1st century BCE the Roman Gaius Maecenas is said to have built the first heated swimming pool.",
          "The lack of swimming in Europe during the Middle Ages is explained by some authorities as having been caused by a fear that swimming spread infection and caused epidemics. There is some evidence of swimming at seashore resorts of Great Britain in the late 17th century, evidently in conjunction with water therapy. Not until the 19th century, however, did the popularity of swimming as both recreation and sport begin in earnest. When the first swimming organization was formed there in 1837, London had six indoor pools with diving boards. The first swimming championship was a 440-yard (400-metre) race, held in Australia in 1846 and annually thereafter. The Metropolitan Swimming Clubs of London, founded in 1869, ultimately became the Amateur Swimming Association, the governing body of British amateur swimming. National swimming federations were formed in several European countries from 1882 to 1889. In the United States swimming was first nationally organized as a sport by the Amateur Athletic Union (AAU) on its founding in 1888. The Fédération Internationale de Natation Amateur (FINA) was founded in 1909.",
          "Internationally, competitive swimming came into prominence with its inclusion in the modern Olympic Games from their inception in 1896. Olympic events were originally only for men, but women’s events were added in 1912. Before the formation of FINA, the Games included some unusual events. In 1900, for instance, when the Games’ swimming events were held on the Seine River in France, a 200-metre obstacle race involved climbing over a pole and a line of boats and swimming under them. Such oddities disappeared after FINA took charge. Under FINA regulations, for both Olympic and other world competition, race lengths came increasingly to be measured in metres, and in 1969 world records for yard-measured races were abolished. The kinds of strokes allowed were reduced to freestyle (crawl), backstroke, breaststroke, and butterfly. All four strokes were used in individual medley races. Many nations have at one time or another dominated Olympic and world competition, including Hungary, Denmark, Australia, Germany, France, Great Britain, Canada, Japan, and the United States.",
          "Competition area:-",
          "Swimming pool:-",
          "competitive swimming events can take place in both 25 metre and 50 metre pools.",
          "Lanes:-",
          "each swimming pool is split into eight separate lanes of 2.75 m and the outer lanes must have an additional empty space of 40 cm of water.",
          "Ropes:-",
          "the outer lanes must have a green rope, four blue ropes for lanes 2, 3, 6 and 7, and three yellow ropes for lanes 4 and 5. The last five metres of the ropes are red to indicate the end of the pool.",
          "Starting block:-",
          "the top of the starting platform should not be less than 50 cm by 50 cm and slope no more than 10°. The entire surface of the platform should be covered with a permanent non-slip material.",
          "types of swimming:-",
          "Freestyle:-",
          "Also known as the front crawl, this is the classic swimming posture. Lie on your stomach and flutter your legs while alternating the arms in a windmill motion. You propel yourself forward with moderate speed in a specific direction. The freestyle is a great competitive and exercise stroke, and allows you to swim longer distances without exhaustion.",
          "Backstroke:-",
          "Lie on your back and flutter your legs while circling your arms in a windmill motion. It’s very similar to the freestyle, but you swim on your back and propel yourself backwards. Many doctors recommend this technique to those who have back problems, or to develop stronger back muscle. This can be a more difficult stroke, though, so consider getting private swim lessons to learn the proper technique.",
          "Breaststroke:-",
          "Float with your stomach facing down, then move your arms in a half-circle motion in front of the body. Bend your legs, then kick back with good timing, and you’ll propel yourself up and forward. This is a great workout and is recommended for those who swim for exercise.",
          "Butterfly:-",
          "An excellent workout and common competitive stroke–possibly because it tests a mature swimmer–the butterfly is performed by bringing your arms up above your head, then pushing them down into the water to propel yourself forward. Your legs perform a dolphin kick, in which they stay together and kick simultaneously in a bobbing fashion. This is a very difficult stroke to learn, but if you take swimming classes in private, you can work diligently to learn this challenging stroke. A swimming teacher will help you learn proper technique and guide you until you perfect it.",
          "Sidestroke:-",
          "Although not one of the official four strokes in competitive swimming, the sidestroke is a great survival technique. This is commonly used by lifeguards because you can hold onto another person and keep them above water while you swim. Lie on your side and scissor your legs to propel yourself forward. It’s a great leg workout because your legs do most of the propulsion. Alternate by meeting your hands in front of your chest, then darting your arms outward, one back and one forward. This can be challenging to learn, but important for helping others."
        ],
        "Rules": [
          "Rules:-",
          "The technical rules of swimming are designed to provide fair conditions of competition and to promote uniformity in the sport. Each swimming stroke has specific rules designed to ensure that no swimmer gets an unfair competitive advantage over another swimmer.",
          "Trained officials observe the swimmers during each event to ensure compliance with these technical rules. If a swimmer violates the rules, and in doing so, is observed by an official, a disqualification (DQ) will result. This means that the swimmer will not receive an official time and will not be eligible for an award in that event. A disqualification may result from actions such as not getting to the starting blocks on time, false starting, performing strokes in an illegal manner, or unsportsmanlike conduct.",
          "Disqualifications are also a result of technical rules violations.",
          "These include :-",
          "freestyle:-",
          "stepping or walking on the bottom of the pool, pulling on the lane rope, not touching the wall on a turn, or not completing the distance.",
          "backstroke:-",
          "not remaining on the back throughout the swim except when turning, pulling or kicking into the wall once turning past the vertical onto the breast, turning onto the breast before touching the wall with the hand at the finish of the race.",
          "breaststroke:-",
          "not swimming on the breast, an illegal kick such as flutter, dolphin, or scissors, non-simultaneous movements of the arms, taking two arm strokes or two leg kicks while the head is underwater, or touching with only one hand at the turns or finish instead of two.",
          "butterfly:-",
          "non-simultaneous movements of the arms or legs, pushing the arms forward under the water instead of over the water surface, using a breaststroke-style kick, or touching with only one hand at the turns or at the finish instead of two.",
          "Officials:-",
          "A swimming competition requires a large number of volunteers to support the running of the day.",
          "These include:-",
          "Starter:-",
          "they maintain control of the swimmers at the moment the referee hands them over. From this point they will ensure a safe and fair start for all.",
          "Clerk of course:-",
          "these people line up competitors in correct order, ready for starting",
          "Timekeepers:-",
          "these are assigned to every lane and provide official times for all competitors. They will not be used if a venue has a fully automated timing system.",
          "Inspectors of turns:-",
          "one inspector of turns is assigned to one or more lanes at each end of the pool. Each inspector of turns ensures that swimmers comply with the relevant rules for turning as well as the relevant rules for start and finish of the race.",
          "Judges of stroke:-",
          "these are located on each side of the pool. They ensure that the rules related to the style of swimming designated for the event are being observed, and observe the turns and the finishes to assist the inspectors of turns.",
          "Finish judges:-",
          "these determine the order of finish and make sure the swimmers finish in accordance with the rules (two hands simultaneously for breaststroke and butterfly, on the back for backstroke, etc)."
        ],
        "Supplements": [
          "Supplements:-",
          "1. Whey protein supplements.",
          "2. Sports drink supplements.",
          "3. Electrolyte supplements.",
          "4. Energy gels or drink supplements.",
          "5. Energy bars.",
          "6. Recovery drink supplements.",
          "7. Multivitamin supplements.",
          "8. Creatine supplements.",
          "whey protein:-",
          "You see, when we work out we usually have some form of external force applying resistance onto our muscles, whether it may be the water we swim in, our own bodyweight from doing exercises like pull-ups, or maybe the resistance created by lifting weights.This resistance creates little micro-tears in the muscle tissue which then needs to be repaired in order for you to become stronger and also recover for the next time you work out. These tears are also the reason you may feel sore after a good workout in case you were wondering.",
          "Sports drink supplements:-",
          "Then we have sports drinks that contain branched amino acids, also known as BCAA’s which also aid in improving performance and recovery after exercise.Then lastly, we have in-workout sports drinks which is my favorite type, these help to improve performance and prevent dehydration by supplying you with nutrients that aid you in staying on top throughout your workout so that you’ll never completely tire out and can train at your max.",
          "Electrolyte powder supplements:-",
          "Some of the functions of electrolytes include regulating nerve and muscle function which is important for any athlete, hydrating the body for optimal performance, and helping to balance blood acidity and pressure as well as rebuilding damaged tissue in your body.Either way, the decision is up to whether you’d like to use a combination of the two or only one type. Alternatively, you can also test out which works better for you by trying both at some point or another.",
          "Multi-vitamin supplements:-",
          "During the times when it’s on the lower end we are prone to getting sick or not feeling well. This will cause us to have to take time off from the pool which will result in less training time and inevitably lower results when the time to race comes.We can, however, give our immune system a boost by supplementing with multi-vitamins that will help to keep us healthy and strong so that we won’t get sick or have to take time off from racing."
        ],
        "Awards_Honours": [
          "Awards and Honours:-",
          "World Swimmers of the Year",
          "American Swimmers of the Year",
          "European Swimmers of the Year",
          "Pacific Rim Swimmers of the Year",
          "African Swimmers of the Year",
          "World Disabled Swimmers of the Year"
        ]
      },
      {
        "id": 8,
        "Sport_Name": "Weightlifting",
        "History": [
          "History:-",
          "In ancient times, basically the Pre-Olympic era,The competition to establish who can lift the heaviest weight has been recorded throughout civilization, with the earliest known recordings including those found in Egypt, China, India and Ancient Greece. Today, the modern sport of weightlifting traces its origins to the European competitions of the 19th century.Weightlifting was first introduced in the Olympics in the 1896 Athens Olympic Games as a part of track and field, and was officially recognized as its own event in 1914. The 1960s saw the gradual introduction of exercise machines into the still-rare strength training gyms of the time.",
          "Indian representatives:-",
          "1.Karnam Malleswari:-Bronze medal in the 2000 Summer Olympics at Sydney.",
          "2.Mirabai Chanu:-Silver medal in the 49 kg weightlifting category at Tokyo Olympics in Japan."
        ],
        "Rules": [
          "Rules:-",
          "1.There are two stages in modern Olympic weightlifting-the snatch and the clean and jerk.The snatch is where the weightlifter picks up the barbell and lifts it above his head in one singular motion.",
          "2. In the clean and jerk, the weightlifter is first required to pick up the barbell and bring it up to his chest (clean). The lifter  must then pause and extend his arms and legs to lift it above the head (jerk) with a straight elbow and have to hold it there until a buzzer is sounded.",
          "3. A weightlifter is given three snatch attempts and three clean and jerk attempts each. A weightlifter’s best attempt at snatch and the clean and jerk are then added up and the one with the highest combined weight lifted is declared the winner.",
          "4. In case two participants have lifted the same combined weight, then the one with the lower bodyweight is declared the winner. In the event of the bodyweight also being equal, the one with lesser attempts will be the winner.",
          "5. A participant is allowed to increase the weight for his next attempt after a successful lift. The one who decides to lift the lowest weight in the first attempt is allowed to go first and he must attempt to lift within one minute of his name being called out in any tournament.",
          "6. The barbell is made of steel and the heavy weights, covered with rubber, are added to the sides.",
          "7. Weightlifters are allowed to use tapes to cover parts of their body – like the wrists and thumbs – to prevent injury. They also often rub chalk on their hands to make it dry before a lift, which prevents the barbell from slipping.",
          "Scoring System:-",
          "1. There are two categories snatch and clean & jerk Snatch: Need to lift the weight in a single motion Clean & jerk: In clean, you need to lift weights to the shoulder level, and in jerk, you need to take the weights from the shoulder level to above your head and control the lift.",
          "2. Each athlete gets three attempts to lift each weight.",
          "3. Three judges are there to judge the lift Lift is considered to be successful when the lift is in control and arms are stretched out properly during jerk.",
          "4. If the lift is successful, white light goes off, which means that the lift was successful and other things to be noted, it is enough if two out of three judges give white light to award it as a good lift.",
          "5. If the lift is unsuccessful, the red light goes off, and only that weight is recorded for that lift where the lifter got white light.The highest weight lifted in the snatch and the highest weight lifted in clean&jerk is combined. The rankings are made according to the highest combined weight value. If the person does not lift the asked weight in three attempts, he is deemed to get 'did not finish' next to his name and will be disqualified."
        ],
        "Supplements": [
          "Supplements:-",
          "When it comes to maximizing size and strength gains,weighlifting players need supplements which are benefitial for their endurance and strengths.Some of the names are",
          "1.Protein – muscle building and fat loss",
          "2.Creatine – boosts your power output and increases water retention in your muscles.",
          "3. Vitamin D and K2 –  improve bone strength and decrease calcium build-up in your blood vessels.",
          "4. Beta-alanine – can help with endurance and possibly building muscle.",
          "5. Berberine – improves insulin sensitivity.",
          "7. Magnesium – positive influence on blood pressure"
        ],
        "Awards_Honours": [
          "Awards and Honours:–",
          "Arjun award",
          "Dronacharya Award",
          "Maulana Abul Kalam Azad Trophy ",
          "Major Dhyan Chandra Khel Ratna award"
        ]
      },
      {
        "id": 9,
        "Sport_Name": "Archery",
        "History": [
          "History:-",
          "Archery is one of the oldest arts still practised today.The history of the bow and arrow is entwined in the history of humanity. Archery initially emerged as a technique for hunting and then later for warfare. The earliest evidence of archery – arrowheads made of flint – dates back to around 20,000 BC. It’s possible that early humans were using bows and arrows even earlier.",
          "Distinctive styles of equipment and technique developed in almost every region of the world. In Asia, where warriors were often mounted on horseback, shorter composite bows became popular, while longbows made of yew made England a military power through much of the Middle Ages. Large communities of archers shooting traditional bows remain active today.",
          "Archery became obsolete in warfare with the advent of gunpowder and quickly developed into a sport.",
          "The first-known archery competition that we can relate to modern times was held in Finsbury, England, in 1583 and had 3000 participants. Archery first featured at the modern Olympic Games from 1900 to 1908 and in 1920. World Archery was founded in 1931 to secure the sport a permanent place on the programme, which was achieved in 1972.",
          "Myths and legends:-",
          "Archery is often featured in myths and legends, as well as modern literature and film.",
          "The bow and arrow often symbolise control, precision, self-reliance and patience, qualities that have resonated in heroic characters – both fictional and real – for millennia. The legends of Odysseus, the Amazons, Arjuna, Ullr, Hou Yi and Nasu no Yoichi are linked by the values of the sport, despite coming from very different parts of the world.",
          "One of the best-known mythological archers is Robin Hood, a champion of the people who is famously said to have taken from the rich to give to the poor. The story originated in England in the Middle Ages and is still retold in modern films and television programmes today.",
          "More modern stories that include archers include The Lord of the Rings and The Hobbit, Arrow and The Avengers. Katniss Everdeen, the main character in The Hunger Games, is credited with boosting archery’s recent popularity among young women.",
          "Archery at the Olympics, Paralympics and World Games:-",
          "Archery featured on the programme of the Olympic Games in 1900, 1904, 1908 and 1920. It returned in 1972 after a 52-year hiatus and has remained on the programme ever since. Athletes compete in target archery events with recurve bows at the Olympics. The winningest archery Olympians are Hubert van Innis of Belgium, including results from the early era, and Kim Soo-Nyung of Korea. Darrell Pace of the USA is the only archer to have won the individual Olympic title twice. Korea is archery’s most successful nation at the Olympic Games.",
          "Archery has featured on the programme of the Paralympic Games since its first edition in 1960 and is rooted in the history of the Paralympic movement, having been used by Dr. Ludwig Gutmann as a rehabilitation activity at Stoke Mandeville Hospital in England, where early versions of the event were held. Impaired athletes compete in para archery events with recurve and compound bows at the Paralympics.",
          "Archery has featured on the programme of the World Games since 1985. Recurve and barebow archers competed in field archery events until 1995, when the compound bow was added. In 2013, the compound competition was changed to the target archery discipline. Morgan Lundin is the winningest archer at the World Games, having won the compound men’s field archery event three times: in 1993, 1997 and 2005.",
          "Indian's archerers:-",
          "Atanu Das",
          "Deepika Kumari",
          "Ankita Bhakat",
          "Komalika Bari"
        ],
        "Rules": [
          "Rules:-",
          "1. Archers must adhere to all official rules in terms of the equipment they use in the performance of their sport, with the main emphasis being on them using no equipment or accessories that would give an unfair advantage over an opponent.",
          "2. The maximum time permitted to shoot an end of three arrows is two minutes, and four minutes for an end of six arrows.",
          "3. Athletes may not raise the bow arm until the signal to start is given and penalties can be given – in the form of points forfeits – if the bow is drawn after the official practice has been closed.",
          "4. An arrow cannot be re-shot under any circumstances. The arrow may be considered not to have been shot if it falls from the bow or misfires, or if the target blows or falls over. Extra time would be given in such circumstances.",
          "5. An arrow that rebounds or hangs from the target will still score based on the mark it makes on the target face. Arrows that stick – Robin Hood-style – in the nock of another shall score the same as the arrow in which they are embedded.",
          "6. Athletes can be disqualified, have points deducted or be banned from competition for various breaches of rules, based on the severity of the offence.",
          "7. If equipment is damaged, appeals can be made to the judge for such equipment to be replaced or fixed, and any time allowances will be at the judge’s discretion.",
          "Some other rules:-",
          "All standard long bows, recurve bows, compound bows and crossbows are acceptable on the range. 380 and 400 compound bows must shoot in the posted dedicated lanes.",
          "Family members under 16 must be accompanied by an adult member.",
          "Always draw the bow pointed toward the target, with or without arrows.",
          "Avoid physical contact with an archer in the shooting position.",
          "Do not shoot arrows up into the air.",
          "Do not use damaged equipment.",
          "Never use arrows that are too short for your draw length. Do not use cracked arrows.",
          "Wait behind the shooting line until all archers are finished shooting and the signal to collect is given.",
          "Never handle another archer’s equipment without permission.",
          "No broached or expandable arrows.",
          "No broadheads.",
          "Do not cross the shooting line to retrieve arrows until everyone is done shooting.",
          "Equipment:-",
          "The bowstring may have any number of strands as long as it fits the bow, and an adjustable arrow rest and a bow sight may also be used. There is little restriction over the types of arrows used, other than those that may cause undue damage to targets, though the maximum diameter of the arrow shaft should not exceed 9.3mm and the diameter of the tips should not exceed 9.4mm. The athletes’ arrows should all be marked with his or her name or initials on the shaft and all arrows used by a competitor in a particular round (or “end”) should be identical.",
          "Scoring in archery:-",
          "Archery is scored by valuing each ring of the archery target that the archers shoot at to score points. the centre ring is worth 10 points and the rest of the ring are in sequencial order from 9-1 inside to outside. If the arrow misses the target, no score is scored",
          "The archers shoot the arrow at the target, usually placed some distance away(70 metres in the olympics) the closer to the centre the arrow is on the target, the more points the archer earns. the centre of the target is worth 10 points and the each ring outwards is one point less."
        ],
        "Supplements": [
          "Supplements:-",
          "Carrots: Promote healthy eyesight, which is important during a match",
          "Foods with Zinc: Studies have shown that 20 mg of zinc a day can improve hand-eye coordination. Food that contain zinc include oysters, pumpkin seeds, whole grains, sunflower seeds, animal proteins, beans, nuts and almonds.",
          "Vitamin C: Found in high amounts in peppers and citrus fruits to aid muscle repair. Food that contain vitamin C include-Broccoli, Peppers (Yellow Bell Peppers), Guavas, Kiwifruit, Berries (Strawberries), Citrus Fruits (Oranges), Tomatoes (Cooked), Papaya.",
          "Choline: Tomatoes, egg yolks and potatoes are all high in choline, a member of the vitamin B family. It feeds your brain’s neurotransmitters and has been proven to improve reaction times.",
          "Vitamin A: Because it helps to make new white blood cells. Your body is going to need these to fight off infection and recover from the intense workouts. Vitamin A helps in fixing any micro tears in your muscles. Sweet Potato (Cooked), Carrots (Cooked), Cos or Romaine Lettuce, Dried Apricots, Cantaloupe Melon.",
          "DMAE: Feed your brain something named dimethylaminoethanol, which is found in certain fish. This brain food is a neurotransmitter, which helps messages move across your nerves and brain. DMAE deals with the process required for remembering tactics, techniques and course sequences. Good natural sources of DMAE are salmon, sardines, and anchovies. • Sprouts: The health benefits of eating sprouts are numerous as they are a rich source of protein, anti-oxidants and other vitamins. Sprouting can be done with various vegetables and legumes. Most of us eat sprouts as a morning breakfast, evening snack or sometimes an afternoon meal by adding them to a certain dish.",
          "  Milk: The body cannot make calcium, so the dairy foods (milk, cheese, yoghurt) that children eat and drink every day are important. Calcium is needed for strong and healthy bones.",
          "Dry Fruits: Dry fruits are traditionally known to be a powerhouse of nutrients.",
          "Almonds have many health benefits for players, handful of soaked almonds improve our memory. • Including walnuts in your diet everyday can boost brain health and Walnuts are rich in B-vitamins and antioxidants that fight free radical damage.",
          "Dates, don’t miss your date with this Iron-rich dried fruit",
          "say no to :- junk food like pizza, burger etc"
        ],
        "Awards_Honours": [
          "Awards and Honours:-",
          "highest award given in archery in india is Major Dhyan Chand Khel Ratna Award",
          "Other awards are:-",
          "Gold star",
          "Black shield with gold star",
          "Blue shield with gold star",
          "Red shield with gold star"
        ]
      },
      {
        "id": 10,
        "Sport_Name": "Golf",
        "History": [
          "History:-",
          "While the modern game of golf originated in 15th-century Scotland, the game's ancient origins are unclear and much debated. Some historians trace the sport back to the Roman game of paganica, in which participants used a bent stick to hit a stuffed leather ball.",
          "The first games of golf were played in Scotland in a kingdom named Fife. Golf was played with sticks, pebbles, and rabbit holes, and King James II hated all the fun because it interfered with wartime.",
          "Golf clubs carved from wood made their debut in Scotland. King James IV was much more onboard with golf as he hired a bowmaker to make him his own set of clubs.",
          "Golf first came to the United States. The Royal Gazette in New York advertised clubs and balls to the select few Americans who were interested in playing the game at the time.",
          "Dr. Robert Adams Paterson improved the game with the invention of gutta percha golf balls. These were made from rubber, weren’t very expensive to make, and were also known as gutties.",
          "The first game of golf took place in the 15th Century in Fife, a Scottish kingdom known for beautiful cathedrals, rolling hills, and fishing villages. Players hit a pebble around a grassy field full of sand dunes and rabbit holes.Since then, golf has become a bit more sophisticated. The modern version was first played at the Royal and Ancient Golf Club in St. Andrews, Scotland in 1754. They came up with the rules and created actual courses for playing.It wasn’t long before other clubs started opening throughout Europe and North America. From that point on, it was official – golf was a pastime that was here to stay!",
          "Some indian's Players are:-",
          "Anirban lahiri",
          "Aditi Ashok",
          "Jyoti Randhawa",
          "Jeev milkha singh"
        ],
        "Rules": [
          "Rules:-",
          "The main rule of golf is to play fair. Even on the back cover of the rule book it states to 1) play the course as you find it 2) play the course as it lies and 3) if you can't do either, do what is fair. So fairness is a key to golf. There will be times when playing golf that you are tempted to cheat. Standing out in the woods and your ball is right behind a tree, the temptation to kick the ball over a few feet to get a good shot. Don't do it! Golf is a game of etiquette and conscience. The game will be more rewarding if you always play by the rules and play fair.",
          "Rules are:-",
          "1.You must play the golf ball where it lies, unless there is a rule that allows you to move it.",
          "2.The golf course may not be changed to gain an advantage, unless there is a rule that allows for a specific change.",
          "3.If your ball is in a bunker or water hazard, your golf club cannot touch the ground or water prior to your actual swing. If it does, you must take a penalty stroke.",
          "4.If you accidentally play the wrong golf ball (oops!), you get a two stroke penalty.",
          "5.On the green, you may mark and lift your ball to clean it or get it out of another golfer's way. When putting the ball must not hit the flag. If the golf ball does hit the flag, it is a two stroke penalty. If you loose the ball in a water hazard, you can drop the ball behind the hazard and in line with the golf hole. You must take a penalty stroke.",
          "6.If you loose the ball out of bounds, you can take a penalty stroke and then replay the shot.",
          "7.If your ball is unplayable, you may take a penalty stroke and then drop the golf ball behind where the ball was and in line with the hole or drop the golf ball within two club lengths.",
          "8.You are allowed a maximum of 14 clubs in your golf bag.",
          "9.Golfers must tee off behind and between the tee markers. Never in front of the tee markers.",
          "10.In addition to the rules of golf, golfers also need to adhere to the etiquette of golf. Fixing divots, not hitting into other players for safety, yelling fore if you do, being quiet while a golfer is hitting the ball, and playing at a good rate are just a few rules of the etiquette of golf that make the game more enjoyable for everyone.",
          "Equipments:-",
          "Balls",
          "Golf clubs",
          "Ball markers",
          "Tees",
          "Golf bags",
          "Golf cart",
          "Towels",
          "Club head covers",
          "Ball mark repair tool",
          "Scoring System in golf:-",
          "In brief, the aim of golf is to complete the course in as fewer strokes as possible; your golf score.",
          "Each hole has a par. The par for each hole defines the guideline number of strokes that should be taken to complete that hole. Par usually ranges from 3 to 5 depending on the physical length of the hole.",
          "Your golf score is the number of strokes that you take to complete the hole. Your final golf score for your round of golf is the sum of the strokes for all holes on the course, plus any penalties (See penalty strokes) you may have incurred."
        ],
        "Supplements": [
          "Supplements:-",
          "In accordance with the Titleist Performance Institute (TPI), my formal education on supplements, and personal use, below is some guidance on these important questions.",
          "Some supplements to consider:-",
          "1. Multi-Vitamin",
          "2. Fish Oil",
          "3. Vitamin D",
          "4. L-Glutamine",
          "5. Whey Protein",
          "6. Creatine",
          "Multi-Vitamins:-",
          "During the day, a lot of people do not ingest all of the proper vitamins and minerals that should be in their diet. Not getting essential vitamins and minerals will cause a person to become deficient in these items, resulting in a breakdown in the metabolic pathway. With a breakdown in your metabolism, one’s performance will decrease quickly. Therefore, by incorporating a high-quality multi-vitamin with breakfast, you will reap the highest benefits, especially during performance, such as walking 18 holes during a tournament round.",
          "Fish Oil",
          "Fish oil is a form of fatty acid that is derived from the tissues of oily fish. It contains Omega-3 fatty acids, eicosapentaenoic acid (EPA), and docosahexaenoic acid (DHA). Here are 10 reasons why fish oil is an essential supplement to take",
          "Vitamin D",
          "Vitamin D promotes bone growth. Too little vitamin D results in soft bones, especially in children, and fragile bones in adults. Also, Vitamin D deficiency has been liked to breast cancer, colon cancer, prostate cancer, heart disease, depression, and weight gain. To prevent all of the issues that comes with deficiency, make sure you get an adequate amount of Vitamin D. I would recommend getting Vitamin D from natural sources such as fish, milk, cheese, butter, whole grains and plenty of sunshine.",
          "L-Glutamine",
          "Glutamine plays key roles in protein metabolism, cell volumizing, and anti-catabolism (breakdown of muscle tissue). Glutamine also increases your ability to secrete Human Growth Hormone, which helps metabolize body fat and support new muscle growth. Active individuals should take 10-15 grams of L-Glutamine per day. To reap the full benefits, especially in the gym, taking L-Glutamine can bring one’s golf game to the next level.",
          "BCAAs (Branched Chain Amino Acids)",
          "All proteins are composed of 20 difference amino acids. There are eight that the body cannot produce, which are isoleucine, leucine, lysine, methionine, phenylalanine, threonine, tryptophan, and valine, these are called essential amino acids. Essential amino acids must be ingested in food, or supplementation, to get them inside the body. BCAAs stimulate the production of insulin. The main function of insulin is to allow the circulating blood sugar to be taken up by the muscle cells and used as a source of energy. BCAAs are also anti-catabolic because they help prevent protein breakdown and muscle loss. In order to maintain muscle, especially after a hard day of golf and fitness, it is important to take a BCAA supplement to prevent the loss of muscle and maintain energy levels. It is recommended that a person take .15-.16g/kg of bodyweight per day.",
          "Whey Protein:-",
          "Taking a whey protein supplement can allow a person to get more protein in their diet, through a powder or shake, to allow for optimum muscle recovery. Whey protein can also help a person lose fat and preserve muscle, increase size and strength in muscles, reduce hunger, and improve immune function. It is best to take a whey protein supplement 30 minutes after a golf session or fitness session. It is suggested that a person take 17-20g per 100 lbs. of body weight.",
          "Creatine:-",
          "The most researched supplement out there is creatine. The general consensus is that creatine is an essential supplement to take. I might even say that it is the number one supplement a person, athlete or not, should take. Here is why",
          "Strength jolt. Creatine helps your muscles build phosphocreatine, which gives you the ability to perform better at shorter, intense, strength building exercises.",
          "Quicker start. It has been shown that creatine can significantly improve a muscles power production by 10% (think about it, creatine may help you hit the ball farther).",
          "Boosts testosterone in men. Testosterone helps a male keep energy, endurance, strength, and mental sharpness in order. Creatine can boost these elements to improve performance.",
          "More productivity. Creatine has been proven to help productivity within the day. That means you can get more out of your golf training, fitness sessions and school work.",
          "There is one misconception out there about creatine: Creatine loading, which means ingesting more creatine than the body needs to give an extra boost, then after the loading period, reducing to the normal amount of five grams per day. This is not effective because when the body has more than normal amounts of a nutrient in the body, it will digest it, and not use it. Therefore, for males and females alike, a person should take five grams of creatine per day taken in the form of creatine monohydrate (the purest form of creatine). Most creatine is unflavored, so I recommend taking the powder form in a fruit juice."
        ],
        "Awards_Honours": [
          "Bob jones award",
          "Joe Dey award",
          "Green Section Award",
          "Herbert Warren Wind Award",
          "IKE Grainger Award"
        ]
      }
     ]


